spring:
  datasource:
    url: jdbc:mysql://localhost:3306/validator?characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: 123456
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
#        web-admin-password: 123456

  messages:
    basename: i18n/common
