version: '3.1'

services:
  mysql:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - ./mariadb:/var/lib/mysql
      # - ./conf:/etc/mysql/conf.d
    ports: 
      - 3306:3306
